const INIT_PAGE = 'INIT_PAGE'
const CLEAR_PAGE = 'CLEAR_PAGE'
const LOADING = 'PAGE_LOADING'
const SET_PAGE_STATE = 'SET_PAGE_STATE'
const GET_LIST = 'PAGE_GET_LIST'
const GET_PAGE = 'PAGE_GET_PAGE'
const RESET_CRITERIA = 'PAGE_RESET_CRITERIA'
const SET_CRITERIA = 'PAGE_SET_CRITERIA'
const SHOW_MODAL = 'PAGE_SHOW_MODAL'
const HIDE_MODAL = 'PAGE_HIDE_MODAL'
const SET_APP_STATE = 'SET_APP_STATE'
const MODAL_LOADING = 'MODAL_LOADING'

// video
const UPDATE_VIDEO_MODAL = 'UPDATE_VIDEO_MODAL'

export {
  INIT_PAGE,
  CLEAR_PAGE,
  LOADING,
  SET_PAGE_STATE,
  GET_LIST,
  GET_PAGE,
  RESET_CRITERIA,
  SET_CRITERIA,
  SHOW_MODAL,
  HIDE_MODAL,
  MODAL_LOADING,
  SET_APP_STATE,
  UPDATE_VIDEO_MODAL
}
